### ISSUE TITLE
Clustered via grouping markers disappear after destroy/create

### ISSUE THREAD

**Issue by ivan-antonyuck** [tombatossals/angular-leaflet-directive#769] opened 2015-05-22 13:20 UTC
I found one more issue with clustering.
If i create a map with clustering via 'group' attribute on marker, and then destroy it with ng-if and then recreate again markers will not appear.

plunker is here:
http://plnkr.co/edit/VmBaz8Qm4GgjCbJR6vAB?p=preview

To replicate uncheck the checkbox and then check it again.
I'm not exactly sure that it is not a leaflet.markercluster.js issue, though.

Upd.:
Replicated in Chrome 41 and firefox 38 and 40 on OS X

**Comment by FabianMeul** [comment] 2015-05-26 09:58
I'm also having this issue. Any updates on this?

**Comment by rasmi** [comment] 2015-06-15 18:14
Still having this issue in the latest 0.8.4 release.

**Comment by nmccready** [comment] 2015-06-15 19:12
Sounds like destroy is not killing all the markers in leafletData when it should.  Sounds like a simple fix.

**Comment by esetnik** [comment] 2015-06-24 14:53
@nmccready I just got hit with the same issue. I'm not too familiar with `angular-leaflet-directive` but can you point me towards the suspect area and i'll work towards a PR?

I found that manually calling the `leafletMarkersHelpers.resetMarkerGroups()` fixes the bug but I believe this is not the proper solution.

```
            getLayers().then(function (layers) {
              var _clean = function (models, oldModels) {
                leafletMarkersHelpers.resetMarkerGroups();
                _destroy(models, oldModels, leafletMarkers, map, layers);
              };
```

**Comment by nmccready** [comment] 2015-06-24 17:00
Might be related to this #815 , please test against master.

**Comment by esetnik** [comment] 2015-06-24 17:06
Unfortunately it is still not working against https://github.com/tombatossals/angular-leaflet-directive/commit/40abcb1bd0ef65e836df4ed6237c09f6a9d01166

**Comment by esetnik** [comment] 2015-07-01 17:04
any updates on this? How can I help?

**Comment by jessertaylor** [comment] 2015-07-03 10:11
Actually *this* is the bug that I also ran into, I can confirm this

**Comment by joeljeske** [comment] 2015-08-28 14:24
Also having this issue. Any ideas or fixes? 

I actually ran into it inside of a UI Router State: the map and marker clusters would load fine the first time but on sequentially views of the state, the markers were not visible.

**Comment by nmccready** [comment] 2015-08-28 14:28
Try using it without watches. 

https://github.com/tombatossals/angular-leaflet-directive/blob/d386b7f8f7bd201e1e3d467d5e61c67045a56570/examples/0605-mixed-overlays-markers-nested-no-watch-example.html#L162

https://github.com/tombatossals/angular-leaflet-directive/blob/d386b7f8f7bd201e1e3d467d5e61c67045a56570/examples/0605-mixed-overlays-markers-nested-no-watch-example.html#L31

If you have multiple updates force them all to wait via $q.all and then call create as linked above. I know this is ideal but it is a possible work around.

**Comment by joeljeske** [comment] 2015-08-28 14:45
Thanks for the quick reply. Unfortunately that does not appear to be working. Here is my setup: 

```js
angular.module('map').controller('MapCtrl', function($scope, $markers){
	// Defined in another block as an array of objects with 'lat', 'lng', and a 'group' property
	$scope.markers = $markers,
	$scope.markersWatchOptions = {
		doWatch: false,
		isDeep: false,
		individual: {
			doWatch: false,
			isDeep: false
		}
	};
	$scope.layers = {
		baselayers: {
			osm: {
				name: 'OpenStreetMap',
				url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
				type: 'xyz'
			}
		},
		overlays: {
			clusters: {
				name: "Orders",
				type: "markercluster",
				visible: true
			}
		}
	}
});
```

```html
<leaflet 
	width="100%"
	height="500px"
	markers="markers"
	markers-watch-options="markersWatchOptions"
	layers="layers">
</leaflet>
```

**Comment by joeljeske** [comment] 2015-08-28 15:51
Here is a sample plunker demonstrating the issue. Toggle between the states and notice the clusters only appear on first viewing. 

http://plnkr.co/edit/NYO66s9kJTowzJhBJLoh?p=preview

**Comment by nmccready** [comment] 2015-08-28 15:56
Thanks for the example; I'll try and find some time to look at it.

**Comment by remast** [comment] 2015-09-13 18:57
+1 from me I noticed this bug too.

**Comment by bampakoa** [comment] 2015-10-08 17:40
+1

**Comment by nmccready** [comment] 2015-10-08 22:17
Please stop with the +1's or I will need to lock the issue. If you really need it immediately please dig into the code.

**Comment by nmccready** [comment] 2015-10-14 18:00
#820 and this are pretty much the same issue I think. Or they are definitely related.

**Comment by tombatossals** [comment] 2015-11-04 07:13
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Closed by tombatossals** 2015-11-04 07:13 UTC
Labels: bug

**Comment by farrago** [comment] 2015-11-05 12:04
I have been investigating this for the last couple of days and I think I know at least part of the reason and I thought I would share in case it helps others or helps with the re-write. Sorry for the length, just wanted to get everything down!

## Summary ##
I believe it's to do with how marker groups are created and **not** destroyed in the `leafletMarkersHelpers` service -v- the maps themselves which **are** created and destroyed.  This leaves `leafletMarkersHelpers` with `groups` that exist in the service but are not attached to a map.

The only workaround I see at present is as per @esetnik: calling `leafletMarkersHelpers.resetMarkerGroups()` whenever you destroy a map.

## Details ##
When you add markers with a `group` you eventually end up in `leafletMarkersHelpers.addMarkersToGroup()` which has this code:
```javascript
if (!isDefined(groups[groupName])) {
    groups[groupName] = new L.MarkerClusterGroup(groupOptions);
    map.addLayer(groups[groupName]);
}
```
This causes the flow through a *create* -> *destroy* -> *recreate* cycle to be:
1. Visit page for the first time
2. *markers* added with `group: myGroup`
3. `addMarkersToGroup()` is called
4. `isDefined(groups['myGroup'])` == *false* so the group is created, and `map.addLayer()` called.
5. `<leaflet>` destroyed (via `ng-if` or navigating to a different `ui-router` view, etc).
6. map **is** removed (via `scope.$on('$destroy...` in the main leaflet directive link function)
7. Importantly `groups['myGroup']` is **not** removed
8. `<leaflet>` added back in (`ng-if`/ `ui-router`)
9. map recreated, markers added, `addMarkersToGroup()` called
10. `isDefined(groups['myGroup'])` == *true* so the group is **NOT** created, and `map.addLayer()` is **NOT** called.
11. We now have a group that doesn't seem to be attached to the map and thus never displays

Using a debugger to make sure the group is recreated in step 10. does indeed cause the groups to show up again, so I'm pretty certain this is the problem.

## Workaround ##
Step 10 is why @esetnik *workaround* of calling `leafletMarkersHelpers.resetMarkerGroups()` works.  It deletes the group, so at step 10 the group doesn't exist and thus gets recreated and added to the map.

There is also an additional problem that `leafletMarkersHelpers.resetMarkerGroup(groupName)` doesn't work because it tries to use `splice` but `groups` is declared as an `Object` not an `Array`.  So you can only delete *all* the groups, and not just *one* group, as the code stands.

For my use-case the workaround of calling `resetMarkerGroups` in my controller's `$destroy` is good enough, but I may have to revisit later.

## Proper Fix? ##
The proper fix is probably to also reset groups *related to this map* in the `scope.$on($destroy...` in the main directive.  However groups are only indexed by name, and not by combination of map and name. So if you have two maps with markers with the same group name they will likely break.  in fact, thinking about it they are probably already broken on the second map (though I haven't tested) because of the same issue (group will not be attached to the second map).

The other options might be to check if the group's layer is already in the map, and if not add it with `addLayer()` but not recreate the group.  However I must confess to not knowing enough of leaflet to know if that is possible or would work (and I haven't tried).

Anyway, hope this helps and feel free to get in touch with any questions and I can try and answer.

**Comment by sam2x** [comment] 2016-09-02 11:55
I feel like this is the bug who is struggling me since days... Any news after more 1 year ? 

The proposal workaround resetMarkerGroup isnt working for me, when i reload/comeback to the page (using ui-router), the marker group disapear (my markers object is correctly populated, if i remove group/type, it works...). 

Any ideas ? I have rebuild manually leaflet/leaflet-markercluster and get the last leaflet-directive release in the hope that the bug was in under layer, but no chance. Please help.

**Comment by sam2x** [comment] 2016-09-02 12:24
resolved!!! holy ****!!! it looks like the '$destroy' events wasnt called in the right time(too late ?), so i used ui-router events which are called before resolve route.
So something like this in the map controller did the trick :  

```
$scope.$on('$stateChangeStart', function () {
    leafletMarkersHelpers.resetMarkerGroups()
})
```

Without your help mentionning group bug & resetMarkerGroups, i would manage to fix it, and i would have certainly moved to another lib. So thx!
