### ISSUE TITLE
How to know the new coordinates when i drag pointer to new location? 

### ISSUE THREAD

**Issue by praveenkumararepalliGit** [tombatossals/angular-leaflet-directive#626] opened 2015-02-09 07:23 UTC
Hi ,

I have read your directive .Its every useful to integrate MAP into website.
Here is a doubt i got when use DRAG feature.
How would i Know the new location coordinates when pointer dragged to new location ?

**Comment by stefan-niedermann** [comment] 2015-02-09 08:14
Hi, look here: http://tombatossals.github.io/angular-leaflet-directive/#!/examples/events

You can watch events. If this does not help you, i can post a piece of code how to listen the drag event and get the new coordinates.

Hint: You don't need to watch leafletDirectiveMap-Event, there is a leafletDirectiveMarker-Event  which you can listen to.

**Comment by praveenkumararepalliGit** [comment] 2015-02-09 09:22
Hi Stefan,
 Thanks for you reply.
Can you post a piece of code .

**Comment by praveenkumararepalliGit** [comment] 2015-02-09 11:20
Hi Stefen,
Actually I wanted to show default location by setting lat = 12 and lng =80;
angular.extend($scope, {
			       city: {
			           lat: 12,
			           lng: 80,
			           zoom: 12
			       },
			       markers: {
			    	   cityName: {
			               lat:12,
			               lng:80,
			               message: "You are here!",
			               focus: true,
			               draggable: true
			           }
			       },
			       defaults: {
			    	   scrollWheelZoom: true
			       },events: {
			            map: {
			                enable: ['zoomstart', 'drag', 'click', 'mousemove'],
			                logic: 'emit'
			            }
			        }
			   });


Here i am watching drag event.
       $scope.$on('leafletDirectiveMarker.drag', function(event){
        var draggedLat=event.targetScope.markers.cityName.lat;
        var draggedLng=event.targetScope.markers.cityName.lng;
        console.log(draggedLat,draggedLng); //here am getting 12 ,80  every time
        console.log(event); // Here i can see new coordinates
        console.log(event.targetScope.markers.cityName.lat,event.targetScope.markers.cityName.lng);
    });
Can you Tell where the issue is ?

**Comment by stefan-niedermann** [comment] 2015-02-09 12:19
sry, can't tell it by rote. i currently don't have access to my notebook. i'll post today evening, hope thats early enough. hmm, maybe the event is wrong? did you try leafletDirectiveMarker.drag**end** ?

**Comment by praveenkumararepalliGit** [comment] 2015-02-09 12:28
Yes Stefen. But Coordinates are wrongs
can I achieve  by doing this code?
Default location is 12,80 once i drop marker to new location still its giving 12,80 only
But dropping point is different 

         $scope.$on('leafletDirectiveMarker.dragend', function(event){
		var coordinatesObject = event;
                var draggedLat=coordinatesObject.targetScope.markers.cityName.lat;
                var draggedLng=coordinatesObject.targetScope.markers.cityName.lng;
        	console.log(draggedLat,draggedLng);
               console.log(event.targetScope.markers.cityName.lat,
                              event.targetScope.markers.cityName.lng);  
         });

**Comment by stefan-niedermann** [comment] 2015-02-09 21:25
I am sorry, i am not able to reproduce this behaviour
```
$scope.$on('leafletDirectiveMarker.dragend', function(event) {
    console.log($scope.markers.mymarker.lat);
    console.log($scope.markers.mymarker.lng);
}
```

this works fine for me...

**Comment by praveenkumararepalliGit** [comment] 2015-02-10 09:55
Yes,i can see the new coordinates only for one image.

I have 3 Images side by side.When click any image making call to 

         $scope.imageLocationDetails(imageData,$index);

Then "imageLocationDetails()" will start executes and there am checking for 

 imageViewPage.jsp

         <leaflet defaults="defaults" markers="markers"  center="city" height="320px" width="320px"></leaflet>


 imageController.js

              $scope.imageLocationDetails = function (image,imageIndex) {
              //Here i can read the EXIF data from Image (EXIF data may have lat and lng)
             $scope.imageIndex = imageIndex;
               if (image.lat && image.lng) {
                     angular.extend($scope, {
			              city: {
			                   lat: latt,
			                   lng: longi,
			                   zoom: 12
			                },
			             markers: {
			                cityName: {
			                          lat:latt,
			                          lng:longi,
			                          message: "You are here!",
			                          focus: true,
			                         draggable: true
			                        }
			                },
			               defaults: {
			                      scrollWheelZoom: true
			                },events: {
			                  map: {
			                      enable: ['zoomstart', 'drag', 'click', 'mousemove'],
			                         logic: 'emit'
			                 }
			           }
			      });
                    } else {
                          angular.extend($scope, {
			       city: {
			           lat: 12,
			           lng: 80,
			           zoom: 12
			       },
			       markers: {
			    	   cityName: {
			               lat:12,
			               lng:80,
			               message: "You are here!",
			               focus: true,
			               draggable: true
			           }
			       },
			       defaults: {
			    	   scrollWheelZoom: true
			       },events: {
			            map: {
			                enable: ['zoomstart', 'drag', 'click', 'mousemove'],
			                logic: 'emit'
			            }
			        }
			   });
                     }

                 }


              $scope.$on('leafletDirectiveMarker.dragend', function(event,gh,mmm){
		      console.log($scope.markers.cityName.lat);
		      console.log($scope.markers.cityName.lng);
		     //Here i wanted to get the latest coordnates and put into image(Based on image ID)
                    $scope.imageList[$scope.imageIndex].lat = 	$scope.markers.cityName.lat;
                    $scope.imageList[$scope.imageIndex].lng = 	$scope.markers.cityName.lng;
                });

Is this correct approach stefen?

**Comment by stefan-niedermann** [comment] 2015-02-10 10:09
hmm @tombatossals any idea?

**Comment by praveenkumararepalliGit** [comment] 2015-02-11 06:08
@tombatossals any Idea ?
could you please check this?

**Comment by praveenkumararepalliGit** [comment] 2015-02-11 07:58
Here is the my requirement Screen shot.
you can see two small images side by side.
when i click any one of the photo i can read lat & lng details .
after that I want change the location of the picture by dragging marker .
Please refer https://github.com/tombatossals/angular-leaflet-directive/issues/626#issuecomment-73672689

![requirement_ss](https://cloud.githubusercontent.com/assets/7676939/6143567/0f6a25fa-b1f1-11e4-97af-e03137636e31.png)

**Comment by sushantkr17** [comment] 2015-03-23 07:17
I am facing the same issue. Please help ??

**Comment by kuanb** [comment] 2015-06-24 14:40
I've got the same issue. My solution was to literally grab the `marker` object from the `dragend` function and hold it as a global variable. This `marker` is then set (or reset) to a global variable. I can access this variable later in other functions to acquire the last known marker location.

Here's my code to show you what I mean:

```
  // Left map listener
  $scope.$on('leafletDirectiveMarker.dragend', function (e, marker) { 
    leftLeafletMarker = marker;
    runMarkerQuerys(marker);
  });

  runMarkerQuerys = function (marker) {
    if (!marker) { marker = leafletMarker; }
    leafletData.getMap('map_left').then(function(map) {
      analystService.singlePointRequest(marker, map, getCompareKey(), function (key) {
        addCompareKey(key);
      });
    });
  }
```

This allows me to run `runMarkerQuerys` regardless of whether or not the user has moved the cursor (except for the first instance, which happens to not be a problem in my specific use case).

**Comment by kuanb** [comment] 2015-06-24 14:42
I should also add that the $scope lat/lngs for the marker being moved do *not* get updated on drag end, so the `console.log()` that was mentioned prior as working has not worked for me - and I was not able to garner any assistance or find any solution on SO, either.

**Comment by tombatossals** [comment] 2015-11-04 07:07
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Closed by tombatossals** 2015-11-04 07:07 UTC

**Comment by sombriks** [comment] 2015-11-06 18:46
hi,

i was about to open an issue but found this one.

when we move the map, center gets updated in a transparent way.

IMO markers with drag enabled should receive the same benefit.

**Comment by tombatossals** [comment] 2015-11-06 20:47
Please @sombriks , could you provide a jsfiddle showing your behaviour? You could use this jsfiddle as a starting point:

http://jsfiddle.net/maistho/9jymzymu/

I'm actually reworking all the code to make it compatible with Leaflet 1.0 and start the compatibility with Angular 2.0, but I can take a look at your problem if it's a bug generic enough.

I  will reopen this issue you provide the jsfiddle. Thanks

**Comment by tsuz** [comment] 2016-02-19 08:47
@kuanb +1 Thanks!

**Comment by Radomiej** [comment] 2016-03-01 17:20
I prepare this behavior: http://jsfiddle.net/9jymzymu/12/

**Comment by paszin** [comment] 2016-05-04 08:26
This solved the problem for me:
When you drag your marker, update the marker location.

```
$scope.$on('leafletDirectiveMarker.mymap.dragend', function(e, args){

            $scope.markers[args.modelName].lat = args.model.lat;

            $scope.markers[args.modelName].lng = args.model.lng;

        });
```

**Comment by radumardale** [comment] 2016-06-24 12:32
I really wanted to get the coordinates in the drag event, not in the dragend event.

After many attempts I ended up using

```
$scope.$on("leafletDirectiveMarker.drag", function (event, args) {
    var point = args.leafletEvent.target._leaflet_events.drag[0].context._latlng;
    console.log(" lat, lng = " + point.lat + ", " + point.lng);
});
```

Not really by the book but works for me.
