### ISSUE TITLE
Version 0.8.7 $scope.center

### ISSUE THREAD

**Issue by Shrizzy** [tombatossals/angular-leaflet-directive#903] opened 2015-08-27 14:46 UTC
Setting the center doesn't seem to be working in the latest release once the map is loaded:
        
    angular.extend($scope, {
                center: {
                    lat: 35.60371874,
                    lng: -37.60345458984,
                    zoom: 2
                }
            });

If I need to change the center after a map is loaded, is there a different/better approach now?

**Comment by nmccready** [comment] 2015-08-27 16:15
I did add some boolean gates to center and bounds. So this is a possible issue. I'll check later for some specs to test both.

**Comment by MarkAPhillips** [comment] 2015-09-01 12:06
Removing line 103 and 104 in center.js seems to fix the issue

```
  if (scope.settingCenterFromLeaflet)
                        return;
```


scope.settingCenterFromLeaflet always seems to be true (except on first load when it is undefined)

**Comment by nmccready** [comment] 2015-09-01 13:13
Yeah I figured that was probably an issue as that was the new code. I'll add some specs and see why it is stuck.

**Comment by nmccready** [comment] 2015-09-01 15:09
I'm testing this against specs and so far I am not seeing an issue. Can you produce your example?

**Comment by nmccready** [comment] 2015-09-01 15:15
Also this example is working fine as well. 

https://github.com/tombatossals/angular-leaflet-directive/blob/master/examples/0101-basic-center-example.html

**Comment by nmccready** [comment] 2015-09-01 15:16
invalid until I get an example to work on; I won't close this just yet.

**Comment by MarkAPhillips** [comment] 2015-09-01 15:32
FYI it may have something to do with the moveend event in relation to the watch event on the scope and how these events occur - in simple scenarios this is not an issue I think but I think in more complex scenarios issues may occur - in my case my application is quite complex based on the requirements I have been provided - which I managed to solve up to version 0.8.5 but since this version I have had regular issues.

 I can provide a MCVE maybe tomorrow but maybe the op can provide an example.

Also what is your reasoning behind adding the boolean gates - is it related to performance?

**Comment by nmccready** [comment] 2015-09-01 15:39
@MarkAPhillips yeah there are unnecessary checks and changes when we know we have just updated from our internal scope or directive. But if it is too much of an issue I can back it out. It might be a digest issue since the switches are turned on/off via a timeout.

**Comment by danielrivera** [comment] 2015-09-01 18:52
I am able to reproduce this issue on my app, and removing those lines fix the problem. I will try to share an example next week.

**Comment by ageblade** [comment] 2015-09-02 08:33
Hi, happens here also.
After some debugging I can see the problem clearly as the 'scope' variable inside the $timeout is actually the leafletscope and not the controller's scope, so it is setting a new variable to false and the true one inside the controller still stays true.

**Comment by nmccready** [comment] 2015-09-02 15:07
@ageblade ahh thanks! easy fix yeah they should both be leafletScope please PR a fix and take credit. Thank you

**Comment by nmccready** [comment] 2015-09-02 19:12
Fixed in #906

**Comment by ageblade** [comment] 2015-09-02 19:17
Hi, I reverted it from #906  as it a little out of context.
Is there any way I can commit it for a different PR ? maybe a brtanch ?

**Comment by nmccready** [comment] 2015-09-02 21:25
Yes just branch your fork from master and pr it to master its easy

**Closed** 2015-09-02 23:57 UTC
Labels: bug, invalid
