### ISSUE TITLE
require.js and commonjs issue & couch potato lazy loading not working

### ISSUE THREAD

**Issue by cscrum** [tombatossals/angular-leaflet-directive#965] opened 2015-09-29 21:58 UTC
I have a project using require.js and couch potato to perform lazy loading for the modules. For some reason, when using the latest version of angular-leaflet with the simple-logging, the entire application will fail to load when I try to include the leaflet-directive in the controller for the map. Using a version prior to the simple-logging requirement works except I'm having the old resizing issue so I want to try the new version. Here are some code snippets...

This is setting up the module:
```
define(['angular',
    'angular-couch-potato',
    'angular-ui-router',
    'ng-table',
    'ngStorage',
    'nemLogging',
    'treeControl',
    'ng-file-upload',
    'leaflet',
    'vincenty',
    'leaflet-directive',
    'd3',
    'line-chart',
    'angular-bootstrap',
    'Bing'
    ], function (ng, couchPotato) {

    "use strict";


    var module = ng.module('app.network', ['ui.router', 'ngTable','ngStorage','treeControl','ngFileUpload','n3-charts.linechart','ui.bootstrap.modal','leaflet-directive']);


    couchPotato.configureApp(module);

    module.config(function ($stateProvider, $couchPotatoProvider) {....

```
If I remove 'leaflet-directive'  from the 
 var module = ng.module('app.network', ['ui.router', 'ngTable','ngStorage','treeControl','ngFileUpload','n3-charts.linechart','ui.bootstrap.modal','leaflet-directive']);

then the application loads, but of course mapping doesn't work. If I simply replace the new angular-leaflet.js with an older version of the file and include the 'leaflet-directive', the the mapping works, however I have resizing issues. Any ideas out there?

**Comment by nmccready** [comment] 2015-09-29 23:11
Try the latest angular-simple-logger as it is now wrapped in a function.

**Comment by nmccready** [comment] 2015-09-29 23:20
Actually the problem is probably related to this; https://github.com/nmccready/angular-simple-logger/issues/7 .

**Comment by nmccready** [comment] 2015-09-29 23:23
Please see the work arounds and I will try to get to fixing it better.

**Comment by nmccready** [comment] 2015-09-29 23:30
This is a valid dependency bug please see the issue stated above as it states the workarounds and the situation.

**Comment by nmccready** [comment] 2015-09-29 23:30
@tombatossals can we add a new label for `dependency bug`?

**Comment by nmccready** [comment] 2015-09-30 18:12
There are updates to this on angular-simple-logger using the PR'd branch as a test bed for you would help me out.

**Comment by cscrum** [comment] 2015-09-30 23:58
I loaded an older version of logger and it all works. I don't really need the logging anyway, so that works out for now. I'd love to try to help but have a really tight deadline for this. In a couple weeks I'll revisit and let you know.

**Comment by nmccready** [comment] 2015-11-02 15:12
This issue was moved to angular-ui/ui-leaflet#121

**Comment by tombatossals** [comment] 2015-11-04 07:16
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Closed by tombatossals** 2015-11-04 07:16 UTC
Labels: bug, workaround
