### ISSUE TITLE
gh-pages is broken

### ISSUE THREAD

**Issue by lavahot** [tombatossals/angular-leaflet-directive#1012] opened 2015-10-31 06:10 UTC
The exact err is: Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=mainPage&p1=Error%3…leaflet-directive%2Fbower_components%2Fangular%2Fangular.min.js%3A19%3A463)

The page with start to render at the top, then go to a white page.

**Comment by nmccready** [comment] 2015-11-02 15:22
This issue was moved to angular-ui/ui-leaflet#141

**Comment by tombatossals** [comment] 2015-11-03 09:06
Working again, I had to revert the angular-leaflet-directive version to an old one until I can investigate which is the cause of the conflict.

**Comment by tombatossals** [comment] 2015-11-03 10:39
Finally solved, we missed the angular-simple-logger dependency of the core directive.

Closing.

**Comment by tombatossals** [comment] 2015-11-03 10:39
Thanks @lavahot

**Closed by tombatossals** 2015-11-03 10:39 UTC

**Comment by lavahot** [comment] 2015-11-04 05:22
NP, my pleasure. Thank *you* for fixing it.
