### ISSUE TITLE
Marker positions don't update when dragging them

### ISSUE THREAD

**Issue by timesqueezer** [tombatossals/angular-leaflet-directive#814] opened 2015-06-20 23:02 UTC
I recently discovered that dragging markers would'nt update their longitude and latitude.
As it appears to be happening on the example pages too, I think it is a general bug.
http://tombatossals.github.io/angular-leaflet-directive/#!/examples/dragging-markers

**Comment by nmccready** [comment] 2015-06-23 16:35
Confirmed.

**Comment by jessertaylor** [comment] 2015-06-24 11:24
Is this a dupe of #690 ?

**Comment by nmccready** [comment] 2015-06-24 14:33
Yes dupe, closing.

**Closed by nmccready** 2015-06-24 14:33 UTC
Labels: bug, duplicate
