### ISSUE TITLE
getNorthWest and getSouthEast in map.getBounds

### ISSUE THREAD

**Issue by daniel-obadia** [tombatossals/angular-leaflet-directive#402] opened 2014-06-27 20:41 UTC
Hi!

Is there a way for me to get the NorthWest and SouthEast object in the map.getBounds function?

When I console.log map.getBounds(); I only seem to be getting the NorthEast and SouthWest lat and lng. 

I read some comments and have been able to get the correct lat and lng that I'm looking for. However, they dont update when the map is dragged as the NorthEast and SouthWest lat and lng update.

How can I use the leafletBoundsHelpers service to get this information?

Here is my current code 

```
  leafletData.getMap().then(function(map) {
    var bounds = map.getBounds();
    var southEast = bounds.getSouthEast();
    var northWest = bounds.getNorthWest();
    console.log (southEast);
    console.log (northWest);

    $scope.southEast = southEast;
    $scope.northWest = northWest;


  var bounds = leafletBoundsHelpers.createBoundsFromArray([
    [ 51.508742458803326, -0.087890625 ],
    [ 51.508742458803326, -0.087890625 ]
  ]);

    <div class="row">
                Latitude northWest: <input type="number" step="any" ng-model="northWest.lat">
                Longitude northWest: <input type="number" step="any" ng-model="northWest.lng">
    </div>
     <div class="row">
                Latitude SouthEast: <input type="number" step="any" ng-model="southEast.lat">
                Longitude SouthEast: <input type="number" step="any" ng-model="southEast.lng">
     </div>

```
Thanks!

**Comment by tombatossals** [comment] 2015-06-30 17:58
Hi @daniel-obadia, sorry for not responding before.

Could you provide a working example of this behaviour, if you still need it? A jsfiddle would be great. I think that the problem is that you need to apply the scopy after modifying the scope.southEast and scope.northWest objects, but it's better confirm it with an example.

Here's a clean jsfiddle to start with:
http://jsfiddle.net/maistho/9jymzymu/

**Comment by nmccready** [comment] 2015-10-29 16:16
This issue was moved to angular-ui/ui-leaflet#26

**Comment by tombatossals** [comment] 2015-11-04 07:02
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.

**Closed by tombatossals** 2015-11-04 07:02 UTC
